CREATE TABLE pokemons.pokemon_table (
  id INT(11) NOT NULL AUTO_INCREMENT,
  name VARCHAR(50) DEFAULT NULL,
  type VARCHAR(255) DEFAULT NULL,
  img MEDIUMBLOB DEFAULT NULL,
  skill1 VARCHAR(255) DEFAULT NULL,
  skill2 VARCHAR(255) DEFAULT NULL,
  skill3 VARCHAR(255) DEFAULT NULL,
  skill4 VARCHAR(255) DEFAULT NULL,
  gender TINYINT(1) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_hungarian_ci;