CREATE DATABASE pokemons
	CHARACTER SET utf8mb4
	COLLATE utf8mb4_hungarian_ci;

CREATE TABLE pokemons.pokemon_table (
  id INT(11) NOT NULL AUTO_INCREMENT,
  name VARCHAR(50) DEFAULT NULL,
  type VARCHAR(255) DEFAULT NULL,
  img VARCHAR(255) DEFAULT NULL,
  skill1 VARCHAR(255) DEFAULT NULL,
  skill2 VARCHAR(255) DEFAULT NULL,
  skill3 VARCHAR(255) DEFAULT NULL,
  skill4 VARCHAR(255) DEFAULT NULL,
  gender TINYINT(4) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 17,
AVG_ROW_LENGTH = 3276,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_hungarian_ci;